- name: disable default redis version
  ansible.builtin.command: dnf module disable redis -y

- name: enable redis 7 version
  ansible.builtin.command: dnf module enable redis:7 -y

- name: install redis
  ansible.builtin.package:
    name: redis
    state: present

- name: allow remote connections to redis
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: update protected-mode to no
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: 'protected-mode'
    line: protected-mode no

- name: restart redis service
  ansible.builtin.service:
    name: redis
    state: restarted