[mongodb]
mongodb.devopsjourney.online

[redis]
redis.devopsjourney.online

[mysql]
mysql.devopsjourney.online

[catalogue]
catalogue.devopsjourney.online

[user]
user.devopsjourney.online

[cart]  
cart.devopsjourney.online   

[shipping]  
shipping.devopsjourney.online 

[frontend]
devopsjourney.online
