- name: disable default nginx version
  ansible.builtin.command: dnf module disable nginx -y

- name: enable nginx 1.24 version
  ansible.builtin.command: dnf module enable nginx:1.24 -y

- name: install nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: start nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: remove default nginx content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: create nginx html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: download the frontend application code
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /tmp/frontend.zip

- name: extract the frontend code
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: remove default nginx configuration
  ansible.builtin.file:
    path: /etc/nginx/nginx.conf
    state: absent

- name: update nginx configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    notify:                                 # Handlers are used to trigger actions when a task changes something. In this case, if the nginx configuration file is updated, we want to restart nginx to apply the new configuration.
      - Restart nginx       




